# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none

variables:
  IISWebSiteName: 'AzureTestProject'

resources:
  pipelines:
    - pipeline: 'buildPipeline'
      project: 'AzureTestProject'
      source: 'Build Pipeline'
      branch: 'main'


stages:
  - stage: 'DeployService'
    displayName: 'Deploy Service'
    pool:
      vmImage: 'window-lastest'

    jobs:
      - deployment: 'DeployService'
        displayName: 'Deploy Service'
        environment: 
          name: 'Windows Server 2026.BaseBuilderAyem'
          resourceType: 'VirtualMachine'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - download: 'buildPipeline'
                  name: 'DownloadBuildArtifacts'
                  displayName: 'Download build Artifacts'
                  artifact: 'AzureTestProject'

                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StopIIS'
                  displayName: 'Stop IIS Service'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: '${{variables.IISWebSiteName}}'
                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployIIS'
                  displayName: 'Deploy IIS Service'
                  inputs:
                    WebSiteName: '${{variables.IISWebSiteName}}'
                    Package: '$(Pipeline.Workspace)\buildPipeline\AzureTestProject\RoundTheCode.AzureTestProject'
                    TakeAppOfflineFlag: true'

                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIIS'
                  displayName: 'Start IIS Service'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: '${{variables.IISWebSiteName}}'
                  